In [1]:
import  numpy as np
import pandas as pd

In [2]:
books = pd.read_csv('../artifacts/Books.csv')

C:\Users\lenovo\AppData\Local\Temp\ipykernel_13428\2474113956.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('../artifacts/Books.csv')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users = pd.read_csv('../artifacts/Users.csv')

In [5]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
ratings = pd.read_csv('../artifacts/Ratings.csv')

In [7]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
books.shape

(271360, 8)

In [9]:
users.shape

(278858, 3)

In [10]:
ratings.shape

(1149780, 3)

check missing values

In [11]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [12]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [13]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

check duplicated values

In [14]:
books.duplicated().sum()

np.int64(0)

In [15]:
ratings.duplicated().sum()

np.int64(0)

In [16]:
users.duplicated().sum()

np.int64(0)

popularity based recommender system

In [17]:
books_with_ratings = ratings.merge(books,on="ISBN")

In [18]:
books_with_ratings.shape

(1031136, 10)

In [19]:
books_with_ratings.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

no of books with same name and different isbn

In [20]:
books_with_ratings.groupby('Book-Title').count()

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Book-Title,,,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",1,1,1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
Ã?Â?sterlich leben.,1,1,1,1,1,1,1,1,1
Ã?Â?stlich der Berge.,3,3,3,3,3,3,3,3,3
Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [21]:
books_with_ratings.groupby('Book-Title').count()["Book-Rating"]

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    4
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Ask Lily (Young Women of Faith: Lily Series, Book 5)                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
                                                                                                             ..
Ã?Â?lpiraten.                                                                                                 2
Ã?Â?rger mit Produkt X. Roman.                                                                                4
Ã?Â?sterlich leben.                                                                                           1
Ã?Â?stlich der Berge.                                                                                         3
Ã?Â?thique en toc                                                                                             2
Name: Book-Rating, Length: 241071, dtype: int64

In [22]:
book_rating_df =books_with_ratings.groupby('Book-Title').count()["Book-Rating"].reset_index()

In [23]:
avg_rating_df = books_with_ratings.groupby('Book-Title').mean('Book-Rating').reset_index()

In [24]:
book_rating_df.rename(columns={'Book-Title':'title','Book-Rating':'num_ratings'},inplace=True)
avg_rating_df.rename(columns={'Book-Title':'title','Book-Rating':'avg_rating'},inplace=True)

In [25]:
book_rating_df.head()

                                               title  num_ratings
0   A Light in the Storm: The Civil War Diary of ...            4
1                              Always Have Popsicles            1
2               Apple Magic (The Collector's series)            1
3   Ask Lily (Young Women of Faith: Lily Series, ...            1
4   Beyond IBM: Leadership Marketing and Finance ...            1

In [26]:
avg_rating_df.head()

                                               title    User-ID  avg_rating
0   A Light in the Storm: The Civil War Diary of ...   51807.25        2.25
1                              Always Have Popsicles  172742.00        0.00
2               Apple Magic (The Collector's series)  198711.00        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...  269557.00        8.00
4   Beyond IBM: Leadership Marketing and Finance ...   11601.00        0.00

In [27]:
avg_rating_df.drop('User-ID',axis=1,inplace=True)

In [28]:
avg_rating_df.head()

                                               title  avg_rating
0   A Light in the Storm: The Civil War Diary of ...        2.25
1                              Always Have Popsicles        0.00
2               Apple Magic (The Collector's series)        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...        8.00
4   Beyond IBM: Leadership Marketing and Finance ...        0.00

In [29]:
pop_df = book_rating_df.merge(avg_rating_df,on='title')

In [30]:
pop_df.head()

                                               title  num_ratings  avg_rating
0   A Light in the Storm: The Civil War Diary of ...            4        2.25
1                              Always Have Popsicles            1        0.00
2               Apple Magic (The Collector's series)            1        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...            1        8.00
4   Beyond IBM: Leadership Marketing and Finance ...            1        0.00

In [31]:
# pop_df1 = pop_df[pop_df['ratings']>=250].sort_values('avg_rating',ascending=False).head(50)
pop_df1 = pop_df.sort_values('avg_rating',ascending=False)

In [32]:
pop_df1

,title,num_ratings,avg_rating
219357,Timelock: How Life Got So Hectic and What You ...,1,10.0
219356,Timelines of World History,1,10.0
20452,Bathroom Game Book,1,10.0
151518,"Rookie Princess (Silhouette Desire, No 483)",1,10.0
151505,Roof World,2,10.0
...,...,...,...
240994,name the baby.,1,0.0
240995,namedropping.,4,0.0
240996,net future,1,0.0
90,'Twas the Night Before Christmas,1,0.0
15,Harry Potter and the Bible: The Menace Behind...,1,0.0

In [33]:
pop_df2 = books[['Book-Title','Book-Author','Image-URL-M']]

In [34]:
pop_df2.head()

,Book-Title,Book-Author,Image-URL-M
0,Classical Mythology,Mark P. O. Morford,http://images.amazon.com/images/P/0195153448.0...
1,Clara Callan,Richard Bruce Wright,http://images.amazon.com/images/P/0002005018.0...
2,Decision in Normandy,Carlo D'Este,http://images.amazon.com/images/P/0060973129.0...
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,http://images.amazon.com/images/P/0374157065.0...
4,The Mummies of Urumchi,E. J. W. Barber,http://images.amazon.com/images/P/0393045218.0...

In [35]:
pop_df2.rename(columns={'Book-Title':'title',"Book-Author":'author','Image-URL-M':'imgurl'},inplace=True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_13428\3694021094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop_df2.rename(columns={'Book-Title':'title',"Book-Author":'author','Image-URL-M':'imgurl'},inplace=True)

In [36]:
pop_df2.head()

,title,author,imgurl
0,Classical Mythology,Mark P. O. Morford,http://images.amazon.com/images/P/0195153448.0...
1,Clara Callan,Richard Bruce Wright,http://images.amazon.com/images/P/0002005018.0...
2,Decision in Normandy,Carlo D'Este,http://images.amazon.com/images/P/0060973129.0...
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,http://images.amazon.com/images/P/0374157065.0...
4,The Mummies of Urumchi,E. J. W. Barber,http://images.amazon.com/images/P/0393045218.0...

In [37]:
pop_50_df = pop_df2.merge(pop_df1,on='title')

In [38]:
pop_50_df

,title,author,imgurl,num_ratings,avg_rating
0,Classical Mythology,Mark P. O. Morford,http://images.amazon.com/images/P/0195153448.0...,2,3.500000
1,Clara Callan,Richard Bruce Wright,http://images.amazon.com/images/P/0002005018.0...,14,4.928571
2,Decision in Normandy,Carlo D'Este,http://images.amazon.com/images/P/0060973129.0...,3,5.000000
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,http://images.amazon.com/images/P/0374157065.0...,11,4.272727
4,The Mummies of Urumchi,E. J. W. Barber,http://images.amazon.com/images/P/0393045218.0...,1,0.000000
...,...,...,...,...,...
270291,There's a Bat in Bunk Five,Paula Danziger,http://images.amazon.com/images/P/0440400988.0...,15,3.800000
270292,From One to One Hundred,Teri Sloat,http://images.amazon.com/images/P/0525447644.0...,1,4.000000
270293,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,http://images.amazon.com/images/P/006008667X.0...,1,0.000000
270294,Republic (World's Classics),Plato,http://images.amazon.com/images/P/0192126040.0...,1,0.000000
270295,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,http://images.amazon.com/images/P/0767409752.0...,1,0.000000

In [39]:
pop_50_df = pop_50_df[pop_50_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50).reset_index(drop=True)

In [40]:
#31:42

In [41]:
pop_50_df

,title,author,imgurl,num_ratings,avg_rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0786222743.0...,428,5.852804
1,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136369.0...,428,5.852804
2,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
4,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139600.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/043936213X.0...,278,5.737410
6,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
7,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/043936213X.0...,278,5.737410
8,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/043920352X.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
10,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/0439567610.0...,347,5.501441
11,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
12,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/0439358078.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439420105.0...,556,5.183453
14,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
15,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064864.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,http://images.amazon.com/images/P/0618346252.0...,368,4.948370
18,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
19,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,http://images.amazon.com/images/P/1565116674.0...,368,4.948370
20,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,http://images.amazon.com/images/P/0395489318.0...,368,4.948370
21,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,http://images.amazon.com/images/P/0618153985.0...,368,4.948370
22,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,http://images.amazon.com/images/P/061826051X.0...,368,4.948370
23,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,http://images.amazon.com/images/P/0618002227.0...,368,4.948370
24,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,http://images.amazon.com/images/P/0618129030.0...,368,4.948370
25,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,http://images.amazon.com/images/P/0618260269.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
27,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0618260277.0...,260,4.880769
29,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0395647398.0...,260,4.880769
30,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0618346260.0...,260,4.880769
31,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0808520903.0...,260,4.880769
32,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0618129081.0...,260,4.880769
33,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. Tolkien,http://images.amazon.com/images/P/0618260595.0...,260,4.880769
34,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
35,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0618002235.0...,260,4.880769
36,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0395489334.0...,260,4.880769
37,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/0618153993.0...,260,4.880769
38,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,http://images.amazon.com/images/P/039527222X.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/006017322X.0...,510,4.700000
40,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0899668585.0...,510,4.700000
41,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446314862.0...,510,4.700000
42,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310492.0...,510,4.700000
43,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0397001517.0...,510,4.700000
44,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0060935464.0...,510,4.700000
45,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/157270036X.0...,510,4.700000
46,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,DAN BROWN,http://images.amazon.com/images/P/0739313126.0...,898,4.642539
48,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
49,The Da Vinci Code,DAN BROWN,http://images.amazon.com/images/P/0739302043.0...,898,4.642539

Collaborative Filtering Based Recommandation System

In [42]:
books_with_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [43]:
user_200 = books_with_ratings.groupby('User-ID').count()['Book-Rating'] > 200

In [44]:
user_200[user_200]

User-ID
254       True
2276      True
2766      True
2977      True
3363      True
          ...
274308    True
275970    True
277427    True
277639    True
278418    True
Name: Book-Rating, Length: 811, dtype: bool

In [45]:
user_rate_great200 = user_200[user_200].index

In [46]:
user_rate_great200

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [47]:
filtered_rating = books_with_ratings[books_with_ratings['User-ID'].isin(user_rate_great200)]

In [48]:
filtered_rating.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...

In [49]:
book_rate50 = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >=50

In [50]:
book_rate50

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                                                                 False
Ã?Â?stlich der Berge.                                                                                         False
Ã?Â?thique en toc                                                                                             False
Name: Book-Rating, Length: 155845, dtype: bool

In [51]:
famous_book = book_rate50[book_rate50].index

In [52]:
famous_book

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [53]:
final_rating = filtered_rating[filtered_rating['Book-Title'].isin(famous_book)]

In [54]:
final_rating.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1165,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
1168,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...
1174,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...

In [55]:
piv_tab = final_rating.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [56]:
piv_tab

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [57]:
piv_tab.fillna(0,inplace=True)

In [58]:
piv_tab

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
similarity_scores = cosine_similarity(piv_tab)

In [61]:
similarity_scores.shape

(706, 706)

In [62]:
similarity_scores[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.13388865,
       0.08303112, 0.11153543, 0.05100411, 0.02517784, 0.11706383,
       0.        , 0.14333793, 0.07847534, 0.06150451, 0.08723968,
       0.        , 0.07009814, 0.13658681, 0.07600328, 0.12167134,
       0.00768046, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01556271, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.11679969, 0.0569124 , 0.08354155, 0.08471898, 0.08785938,
       0.05491435, 0.0548505 , 0.27026514, 0.09779123, 0.06016046,
       0.08958835, 0.06748675, 0.        , 0.04468098, 0.01920872,
       0.        , 0.05629067, 0.00557964, 0.07877059, 0.05219479,
       0.18908177, 0.        , 0.01240656, 0.02984572, 0.04279502,
       0.12680125, 0.16566735, 0.        , 0.13357242, 0.06615478,
       0.        , 0.        , 0.        , 0.10968075, 0.02806606,
       0.04521795, 0.02613277, 0.06876131, 0.01331627, 0.10519138,
       0.03349457, 0.01363458, 0.23669374, 0.        , 0.10397941,
       0.06167753, 0.14176273, 0.11661083, 0.08331012, 0.00850895,
       0.06715433, 0.        , 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.02687779, 0.02175821, 0.        ,
       0.01601663, 0.12114266, 0.04768603, 0.05819184, 0.06510722,
       0.        , 0.0476705 , 0.05273165, 0.0281001 , 0.06524573,
       0.02116345, 0.02097868, 0.07422249, 0.01752778, 0.03734567,
       0.        , 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.        , 0.05995157, 0.02127671, 0.1034119 ,
       0.02766748, 0.10684795, 0.09898722, 0.14145186, 0.05007429,
       0.09428289, 0.01411249, 0.        , 0.07835976, 0.00882242,
       0.04515898, 0.        , 0.01281412, 0.04003334, 0.07477661,
       0.01217906, 0.01887393, 0.02667484, 0.01432864, 0.14702847,
       0.06087282, 0.02578321, 0.02741876, 0.        , 0.14909595,
       0.05606788, 0.        , 0.03199916, 0.03643817, 0.        ,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.08992739, 0.01147457,
       0.02460165, 0.        , 0.18049207, 0.05141892, 0.0477174 ,
       0.10849696, 0.13278139, 0.05915288, 0.05372984, 0.034785  ,
       0.        , 0.09203039, 0.06388401, 0.04773328, 0.15570975,
       0.08420691, 0.12338217, 0.0878469 , 0.08205945, 0.12177532,
       0.02433703, 0.00272862, 0.        , 0.        , 0.03671505,
       0.15280984, 0.0370943 , 0.07458136, 0.09746697, 0.05416091,
       0.10266993, 0.07574414, 0.06426526, 0.0360174 , 0.01559752,
       0.02033559, 0.02463593, 0.        , 0.03349154, 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.01177824, 0.13974105, 0.01978844,
       0.01260824, 0.08608601, 0.04433883, 0.02943085, 0.02242496,
       0.06541868, 0.07866868, 0.14281399, 0.11979305, 0.01858409,
       0.13445377, 0.04809338, 0.09790644, 0.        , 0.17415731,
       0.07437756, 0.        , 0.12389065, 0.01042391, 0.02580849,
       0.        , 0.0895139 , 0.04005551, 0.19182231, 0.02267512,
       0.01730347, 0.03054044, 0.07008822, 0.10084626, 0.10467615,
       0.01683462, 0.12468283, 0.10266459, 0.03549836, 0.02667484,
       0.07652765, 0.08474056, 0.01831977, 0.02177482, 0.15293362,
       0.        , 0.        , 0.01063251, 0.02153089, 0.02946443,
       0.        , 0.02076783, 0.01194825, 0.00953675, 0.2067554 ,
       0.01554292, 0.0390266 , 0.06681046, 0.09014973, 0.05914735,
       0.06206857, 0.        , 0.02005959, 0.07843566, 0.16337845,
       0.07161075, 0.        , 0.14595258, 0.07561631, 0.02939738,
       0.04779629, 0.01807238, 0.11362722, 0.09791273, 0.07999693,
       0.08912337, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02166863, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.        , 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06468143, 0.13904191, 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.06039874, 0.        ,
       0.08996912, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.13439733,
       0.12508514, 0.02329035, 0.0198727 , 0.01105674, 0.02548034,
       0.00896044, 0.08246122, 0.01902896, 0.07025003, 0.0216367 ,
       0.12822982, 0.09998772, 0.08642895, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.        , 0.08982751,
       0.00875634, 0.09923542, 0.10228551, 0.        , 0.12307492,
       0.01758929, 0.02028125, 0.1033827 , 0.13028171, 0.08988894,
       0.09005001, 0.05332049, 0.08033436, 0.04597795, 0.06139888,
       0.02300709, 0.02304904, 0.06523041, 0.01915363, 0.        ,
       0.04542766, 0.        , 0.        , 0.05261954, 0.01317088,
       0.        , 0.        , 0.0485931 , 0.0734819 , 0.10354481,
       0.01718807, 0.09919937, 0.08091989, 0.00358835, 0.04757132,
       0.11122765, 0.05143481, 0.0566614 , 0.        , 0.06087719,
       0.10800615, 0.        , 0.07554686, 0.        , 0.13644384,
       0.04796763, 0.16104067, 0.        , 0.01759864, 0.05438295,
       0.        , 0.08100801, 0.13090711, 0.00581844, 0.07150547,
       0.05428487, 0.06143184, 0.05161653, 0.1951182 , 0.1149488 ,
       0.06513047, 0.06401961, 0.        , 0.        , 0.10853662,
       0.11400426, 0.0463925 , 0.01825277, 0.        , 0.01195201,
       0.21057744, 0.05809707, 0.04349156, 0.02646256, 0.07276403,
       0.05264857, 0.07242165, 0.06790898, 0.01626564, 0.02431809,
       0.02093565, 0.13617057, 0.11784149, 0.08588206, 0.09284352,
       0.11277297, 0.06868983, 0.08200947, 0.13369059, 0.        ,
       0.19972625, 0.02286207, 0.0806288 , 0.        , 0.05756015,
       0.06738056, 0.        , 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.09596456, 0.02180168, 0.02317515, 0.06476149,
       0.07052241, 0.08280452, 0.1700872 , 0.07213921, 0.01172201,
       0.08541218, 0.17990898, 0.08007284, 0.01739625, 0.16728777,
       0.26396194, 0.1840891 , 0.05600273, 0.04133586, 0.06911015,
       0.14456847, 0.22626397, 0.19208896, 0.0239334 , 0.20025064,
       0.01507653, 0.05144282, 0.1233368 , 0.1420166 , 0.02472079,
       0.08563805, 0.02363426, 0.12794024, 0.01083153, 0.07352436,
       0.09532519, 0.03421895, 0.07194212, 0.02297079, 0.15344079,
       0.08856302, 0.        , 0.        , 0.01878656, 0.09772942,
       0.04404359, 0.15211972, 0.0152225 , 0.10307399, 0.05715789,
       0.04600056, 0.06303899, 0.06572303, 0.14421331, 0.08272478,
       0.        , 0.04203701, 0.02276077, 0.17381829, 0.01909967,
       0.16000268, 0.14681486, 0.        , 0.05940546, 0.07725115,
       0.07464763, 0.06546696, 0.07021577, 0.18921368, 0.02494136,
       0.01705027, 0.05437622, 0.04932819, 0.        , 0.11445399,
       0.08001595, 0.12858515, 0.02306658, 0.06129105, 0.02090769,
       0.04550867, 0.1026659 , 0.10725982, 0.0260534 , 0.00173709,
       0.0987294 , 0.08077482, 0.02159226, 0.01614275, 0.0208464 ,
       0.09797466, 0.01906731, 0.18571699, 0.05344577, 0.18925314,
       0.05894189, 0.01488161, 0.1202478 , 0.09840359, 0.01048126,
       0.10596224, 0.07617195, 0.0805439 , 0.        , 0.23299389,
       0.01073642, 0.13573542, 0.04578552, 0.14440017, 0.        ,
       0.12522954, 0.0645501 , 0.02817522, 0.14445559, 0.01721045,
       0.09508161, 0.0517902 , 0.18410818, 0.08704224, 0.10990764,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.00948943, 0.13365876,
       0.05794064, 0.        , 0.06721284, 0.02066998, 0.        ,
       0.01839428, 0.        , 0.12655364, 0.08418288, 0.09095705,
       0.00730589, 0.08143881, 0.        , 0.04218803, 0.08392849,
       0.07785801, 0.        , 0.07151794, 0.02407593, 0.01635126,
       0.03734567, 0.05237227, 0.01140169, 0.00968725, 0.12530648,
       0.00909905, 0.05864096, 0.01769644, 0.12110367, 0.07347567,
       0.04316046])

In [73]:
#to find the index position of book by name
def recommend(book_name):
    #index fetch
    index = np.where(piv_tab.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x : x[1], reverse=True)[0:6]

    data =[]
    for i in similar_items:
        item =[]
        # print(f"Book Title: {piv_tab.index[i[0]]}, Similarity Score: {i[1]}")
        temp_df = books[books['Book-Title'] == piv_tab.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))

        data.append(item)

    return data

In [74]:
recommend('The Da Vinci Code')

[['The Da Vinci Code',
  'Dan Brown',
  'http://images.amazon.com/images/P/0385504209.01.MZZZZZZZ.jpg'],
 ['Angels &amp; Demons',
  'Dan Brown',
  'http://images.amazon.com/images/P/0671027360.01.MZZZZZZZ.jpg'],
 ['Touching Evil',
  'Kay Hooper',
  'http://images.amazon.com/images/P/0553583441.01.MZZZZZZZ.jpg'],
 ['Saving Faith',
  'David Baldacci',
  'http://images.amazon.com/images/P/0446608890.01.MZZZZZZZ.jpg'],
 ["The Sweet Potato Queens' Book of Love",
  'JILL CONNER BROWNE',
  'http://images.amazon.com/images/P/0609804138.01.MZZZZZZZ.jpg'],
 ['Middlesex: A Novel',
  'Jeffrey Eugenides',
  'http://images.amazon.com/images/P/0312422156.01.MZZZZZZZ.jpg']]

In [69]:
np.where(piv_tab.index=='2nd Chance')

(array([2]),)

In [70]:
np.where(piv_tab.index=='2nd Chance')[0]

array([2])

In [ ]:
np.where(piv_tab.index=='2nd Chance')[0][0]

np.int64(2)

In [ ]:
sorted(list(enumerate(similarity_scores[0])),key=lambda x : x[1], reverse=True)[1:6]

[(47, np.float64(0.2702651417103732)),
 (545, np.float64(0.2639619371123497)),
 (82, np.float64(0.23669374347400993)),
 (634, np.float64(0.23299389358170394)),
 (551, np.float64(0.2262639743141286))]

In [ ]:
pop_50_df['imgurl']

0     http://images.amazon.com/images/P/0786222743.0...
1     http://images.amazon.com/images/P/0439136369.0...
2     http://images.amazon.com/images/P/0439136350.0...
3     http://images.amazon.com/images/P/0439139597.0...
4     http://images.amazon.com/images/P/0439139600.0...
5     http://images.amazon.com/images/P/043936213X.0...
6     http://images.amazon.com/images/P/0590353403.0...
7     http://images.amazon.com/images/P/043936213X.0...
8     http://images.amazon.com/images/P/043920352X.0...
9     http://images.amazon.com/images/P/043935806X.0...
10    http://images.amazon.com/images/P/0439567610.0...
11    http://images.amazon.com/images/P/043935806X.0...
12    http://images.amazon.com/images/P/0439358078.0...
13    http://images.amazon.com/images/P/0439420105.0...
14    http://images.amazon.com/images/P/0439064872.0...
15    http://images.amazon.com/images/P/0439064864.0...
16    http://images.amazon.com/images/P/0345339681.0...
17    http://images.amazon.com/images/P/0618346252.0...
18    http://images.amazon.com/images/P/0345339703.0...
19    http://images.amazon.com/images/P/1565116674.0...
20    http://images.amazon.com/images/P/0395489318.0...
21    http://images.amazon.com/images/P/0618153985.0...
22    http://images.amazon.com/images/P/061826051X.0...
23    http://images.amazon.com/images/P/0618002227.0...
24    http://images.amazon.com/images/P/0618129030.0...
25    http://images.amazon.com/images/P/0618260269.0...
26    http://images.amazon.com/images/P/059035342X.0...
27    http://images.amazon.com/images/P/059035342X.0...
28    http://images.amazon.com/images/P/0618260277.0...
29    http://images.amazon.com/images/P/0395647398.0...
30    http://images.amazon.com/images/P/0618346260.0...
31    http://images.amazon.com/images/P/0808520903.0...
32    http://images.amazon.com/images/P/0618129081.0...
33    http://images.amazon.com/images/P/0618260595.0...
34    http://images.amazon.com/images/P/0345339711.0...
35    http://images.amazon.com/images/P/0618002235.0...
36    http://images.amazon.com/images/P/0395489334.0...
37    http://images.amazon.com/images/P/0618153993.0...
38    http://images.amazon.com/images/P/039527222X.0...
39    http://images.amazon.com/images/P/006017322X.0...
40    http://images.amazon.com/images/P/0899668585.0...
41    http://images.amazon.com/images/P/0446314862.0...
42    http://images.amazon.com/images/P/0446310492.0...
43    http://images.amazon.com/images/P/0397001517.0...
44    http://images.amazon.com/images/P/0060935464.0...
45    http://images.amazon.com/images/P/157270036X.0...
46    http://images.amazon.com/images/P/0446310786.0...
47    http://images.amazon.com/images/P/0739313126.0...
48    http://images.amazon.com/images/P/0385504209.0...
49    http://images.amazon.com/images/P/0739302043.0...
Name: imgurl, dtype: object

In [75]:
import pickle

In [ ]:
# pickle.dump(pop_50_df,open("../model/popular.pkl",'wb'))

In [ ]:
# 1;19:43

In [76]:
# pickle.dump(piv_tab,open('../model/pt.pkl','wb'))
# pickle.dump(books,open('../model/books.pkl','wb'))
# pickle.dump(similarity_scores,open('../model/similarty_scores.pkl','wb'))